### ISSUE TITLE
Protection of https://glasswallk8.sharepoint.com/sites/GW-demo-sharepoint

### ISSUE THREAD

**Issue by mahnouman** [k8-proxy/gp-k8-sharepoint#1]
Hello please install this website to a live EC2 server and make/request the necessary DNS changes.
Please make sure that the EC2 instance is having a persistent IP.
We will protect this website using instructions from:
https://github.com/k8-proxy/k8-reverse-proxy/tree/develop/stable-src
The work done here can be of a reference as well:
https://github.com/k8-proxy/gp-engineering-website

**Comment by mahnouman** [comment]
Hello @top-dev-mania please try this task out in your own, meanwhile a senior engineer will join as well.

**Comment by top-dev-mania** [comment]
I came up one issue on run this command.
sudo apt-get update && sudo apt-get install curl git -y
![image](https://user-images.githubusercontent.com/73068626/97548727-2a67ad00-19d8-11eb-99cc-cb1d6f4fcab5.png)

I did resolve by using this command.
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

**Comment by top-dev-mania** [comment]
I installed the 3 dockers to AWS EC2 and tested.
3.135.151.252 is elastic IP address of EC2 and redirected successfully.
I think I should have the account on glasswallk8.sharepoint.com.
![image](https://user-images.githubusercontent.com/73068626/97733505-98979700-1ae0-11eb-9918-0b3e5625d43d.png)
